title: Michael Lanyon's Blog
url: 'https://blog.lanyonm.org'
description: 'Notes and thoughts from LanyonM'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Michael Lanyon'
disqus_shortname: lanyonm
google_analytics: G-NN7JP65RMS

plugins:
  # https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
